---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0 incluye una nueva mejora. 
---
= Novedades en Cloud Volumes ONTAP 9.12.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0 incluye una nueva mejora.

Las últimas versiones de BlueXP también incluyen funciones y mejoras adicionales. Consulte la https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notas de la versión de BlueXP"^] para obtener más detalles.



== 9.12.0 P1 (15 de diciembre de 2022)

Cloud Volumes ONTAP 9.12.0 P1 ya está disponible en AWS y Google Cloud. Esta versión incluye la siguiente función nueva.



=== Compatibilidad con m6id.32xlarge en AWS

Cloud Volumes ONTAP ahora es compatible con el tipo de instancia m6id.32xlarge EC2 en AWS.

Vaya a link:reference-configs-aws.html["página de configuraciones admitidas"] para obtener más información.



== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].



=== Ruta de actualización admitida

Puede actualizar a Cloud Volumes ONTAP 9.12.0 desde la versión 9.11.1. BlueXP le solicitará que actualice los sistemas Cloud Volumes ONTAP aptos a esta versión.



=== Versión necesaria del conector

El conector BlueXP  debe ejecutar la versión 3.9.24 o posterior para implementar nuevos sistemas Cloud Volumes ONTAP 9.12.0 y actualizar los sistemas existentes a esta versión.


TIP: Las actualizaciones automáticas del conector están habilitadas de forma predeterminada, por lo que debería estar ejecutando la última versión.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad no provoca interrupciones y la I/o se realiza de forma ininterrumpida. Durante este proceso de actualización no disruptiva, cada nodo se actualiza conjuntamente para seguir proporcionando I/o a los clientes.




=== Actualizaciones en AWS con tipos de instancia C4, M4 y R4 EC2

En AWS, los tipos de instancia C4, M4 y R4 EC2 ya no son compatibles con las nuevas puestas en marcha de Cloud Volumes ONTAP. Si tiene un sistema existente que se ejecuta en un tipo de instancia c4, m4 o r4, debe cambiar a un tipo de instancia en la familia de instancias c5, m5 o r5. Si no puede cambiar el tipo de instancia, debe activar la red mejorada antes de actualizar.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Aprenda a actualizar en AWS con los tipos de instancia C4, M4 y R4 EC2"^]. link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda a cambiar el tipo de instancia de EC2 para Cloud Volumes ONTAP"^].

Consulte link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Soporte de NetApp"^]para obtener más información sobre el fin de la disponibilidad y el soporte para estos tipos de instancias.
